version: "3.4"
services:
  site:
    image: mindbreez/site:0.1.2
    # build:
    #   context: .
    container_name: site
    command: [ "--noreload" ]
    ports:
      - "6060:8080"
    restart: always
    environment:
      ENVIRONMENT: dev
      POSTGRES_PASSWORD: weee
      POSTGRES_DB: site
      POSTGRES_USER: master
      POSTGRES_HOST: database
      POSTGRES_PORT: "5432"
      SENTRY_SDK: "https://e9a0d61a572543f9ba73e6c509b9343b@o336706.ingest.sentry.io/5409851"
    volumes:
      - ./data:/app/data
    depends_on:
      - database

  database:
    image: postgres:11
    volumes:
      - db_data:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_PASSWORD: weee
      POSTGRES_DB: site
      POSTGRES_USER: master

volumes:
  db_data:
