version: "3.4"
services:
  site:
    # image: mindbreez/site
    build:
      context: .
    container_name: site
    command: [  "0.0.0.0:8080", "--noreload" ]
    ports:
      - "8080:8080"
    restart: always
    environment:
      POSTGRES_PASSWORD: weee
      POSTGRES_DB: site
      POSTGRES_USER: master
      POSTGRES_HOST: database
      POSTGRES_PORT: "5432"
    volumes:
      - ./website/data:/data
  #   depends_on:
  #     - database

  database:
    image: postgres:11
    volumes:
      - db_data:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_PASSWORD: weee
      POSTGRES_DB: site
      POSTGRES_USER: master

volumes:
  db_data:
