# Generated by Django 2.2.7 on 2020-08-28 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mark', models.CharField(default='any', max_length=32)),
                ('Taste', models.CharField(max_length=32)),
                ('Icon', models.CharField(default='fa fa-leaf', max_length=32)),
                ('Mass', models.IntegerField(default=0)),
                ('Have', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flask', models.CharField(choices=[('MILK', 'milk'), ('WATER', 'water'), ('GREEN TEA', 'green tea'), ('ICE', 'ice'), ('VINE', 'vine')], max_length=32)),
                ('Description', models.TextField(max_length=128)),
                ('OptionalList', models.ManyToManyField(blank=True, related_name='OptionalList', to='website.Tabacco')),
                ('TabaccoList', models.ManyToManyField(related_name='TabaccoList', to='website.Tabacco')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mark', models.IntegerField(default=50)),
                ('Date', models.DateField(auto_now_add=True)),
                ('RecipeMark', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RecipeMark', to='website.Recipe')),
                ('TabaccoMark', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TabaccoMark', to='website.Tabacco')),
            ],
        ),
    ]
