# Generated by Django 2.2.7 on 2020-03-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabacco',
            fields=[
                ('TobaccoId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Mark', models.CharField(default='любой', max_length=32)),
                ('Taste', models.CharField(max_length=32)),
                ('Icon', models.CharField(default='fa fa-leaf', max_length=32)),
                ('Mass', models.IntegerField(default=0)),
                ('Have', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('RecipeId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Flask', models.CharField(choices=[('MILK', 'milk'), ('WATER', 'water'), ('GREEN TEA', 'green tea'), ('ICE', 'ice'), ('VINE', 'vine')], max_length=32)),
                ('Description', models.TextField(max_length=128)),
                ('OptionalList', models.ManyToManyField(blank=True, related_name='OptionalList', to='website.Tabacco')),
                ('TabaccoList', models.ManyToManyField(related_name='TabaccoList', to='website.Tabacco')),
            ],
        ),
    ]
