# Generated by Django 2.2.7 on 2020-09-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.CharField(default='fa fa-leaf', max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='tabacco',
            name='Icon',
        ),
        migrations.AlterField(
            model_name='tabacco',
            name='Tastes',
            field=models.ManyToManyField(related_name='TabaccoTastes', to='website.Taste'),
        ),
    ]
