# Generated by Django 2.2.7 on 2020-07-22 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('FeedbackId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('RecipeMark', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='RecipeMark', to='website.Recipe')),
                ('TabaccoMark', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='TabaccoMark', to='website.Tabacco')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedbackList', models.ManyToManyField(blank=True, related_name='FeedbackList', to='website.Feedback')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
