# Generated by Django 2.2.7 on 2020-09-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200920_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Flask',
            field=models.CharField(choices=[('WATER', 'water'), ('MILK', 'milk'), ('GREENTEA', 'green tea'), ('ICE', 'ice'), ('VINE', 'vine')], default='WATER', max_length=32),
        ),
    ]
