# Generated by Django 2.2.7 on 2020-09-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200921_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='id',
        ),
        migrations.AlterField(
            model_name='icon',
            name='Icon',
            field=models.CharField(default='fa fa-leaf', max_length=32, primary_key=True, serialize=False),
        ),
    ]
