# Generated by Django 2.2.7 on 2020-08-23 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_feedback_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
