# Generated by Django 2.2.7 on 2020-08-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='RecipeMark',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RecipeMark', to='website.Recipe'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='TabaccoMark',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TabaccoMark', to='website.Tabacco'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
