# Generated by Django 2.2.7 on 2020-09-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200921_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabacco',
            name='Icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TabaccoIcon', to='website.Icon'),
        ),
    ]
