# Generated by Django 2.2.7 on 2020-09-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_tabacco_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='Icon',
            field=models.CharField(choices=[('DEFAULT', 'fa fa-leaf'), ('ROCKET', 'fas fa-space-shuttle'), ('ANIMAL', 'fas fa-paw'), ('ELEMENT', 'fab fa-elementor'), ('SUPPORT', 'icon-support')], default='DEFAULT', max_length=32, primary_key=True, serialize=False),
        ),
    ]
