# Generated by Django 2.2.7 on 2020-09-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200921_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Tabaccos',
            field=models.ManyToManyField(blank=True, null=True, related_name='RecipeTabaccos', to='website.Tabacco'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Tastes',
            field=models.ManyToManyField(blank=True, null=True, related_name='RecipeTastes', to='website.Taste'),
        ),
    ]
