# Generated by Django 2.2.7 on 2020-09-22 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200922_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
