# Generated by Django 2.2.7 on 2020-11-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200923_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabacco',
            name='Mass',
        ),
    ]
